#!/bin/sh

inputdir="$PWD/input"
prefix="output-"
lastnum=$(find . -maxdepth 1 -name $prefix'*' |
sed -re 's:./output-([0-9]+):\1:' |
sort -n | 
tail -n 1)
newnum=$(expr $lastnum \+ 1)
outputdir="$PWD/$prefix$newnum"
echo "Input dir: $inputdir"
echo "Output dir: $outputdir"


spark-submit build/wordcount.jar $inputdir $outputdir
